ALTER TABLE technical_observations
    ADD COLUMN IF NOT EXISTS return_1d NUMERIC(18,10),
    ADD COLUMN IF NOT EXISTS return_5d NUMERIC(18,10),
    ADD COLUMN IF NOT EXISTS return_20d NUMERIC(18,10);
